[project]
name = "numpy-docstrings-to-html-reference-guide"
version = "0.1.0"
description = "Convert NumPy-style docstrings to an HTML reference guide."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markdown>=3.9",
]
